# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb08a0500ee4029f914dbf346297857108d68b3d7298de5691ab10150dccda63e54a0fd073ed7d2f5fd8fb9052427263c50e6916ff2cc2e60033c1c9cece1d4a

test:
  secret_key_base: e197d9a47ab66eb84aae334be69ea5751fb3d84fd676ba10ac63b0ddee3a62b8d2226726875952c240dc796ffb80f0f6aadd57d88483561f42cc60d78ed5220b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
